#!/bin/zsh
cd csl
./build.sh
cd ..
cd int_essay
./build.sh
cd ..
cd mentor
./build.sh
cd ..
cd now
./build.sh
cd ..
cd path
./build.sh
cd ..
cd recording
./build.sh
cd ..
cd review
./build.sh
cd ..
cd works
./build.sh
cd ..
cd extend
./build.sh
cd ..
cd bridge
./build.sh
cd ..
cd contact
./build.sh
cd ..
# Home page (index.html) is handcrafted — not generated by Asciidoctor. Do not add it here.
