#!/bin/zsh
# The home page (index.html) is handcrafted HTML — it is NOT generated by Asciidoctor.
# Edit index.html directly. This script intentionally does nothing to prevent accidental overwrites.
echo "index.html is handcrafted — edit it directly, do not rebuild from doc/index.adoc."
